### ISSUE TITLE
Ability to break spawner

### ISSUE THREAD

**Issue by SuixideBunneh** [poma123/PickupSpawners#11]
**Describe the bug**
Can we allow default player (without permission and tools) to break spawner like vanilla?It means that the spawner break and did not drop. When they have the correct permission + correct tool, then the spawner will break and drop.

**How to reproduce**
-Without permission, player cannot break the spawner.

**Expected behavior**
Without permission + correct tools, player can break the spawner but did not drop. With permission+ correct tools, player can break the spawner and the spawner drop.

**Screenshots**
N/a

**About your server (please complete the following information):**
 - Server version: Spigot 1.13.2
 - Plugin version: 2.9.7
 - Plugins list : shopgui+, essentials

**Additional context**

**Comment by poma123** [comment]
~~Hmm. Will working on it.~~

**Comment by poma123** [comment]
You can just add pickupspawners.bypasspickupblock permission by default.
