### ISSUE TITLE
Error on pickup

### ISSUE THREAD

**Issue by yaitsbilly** [poma123/PickupSpawners#12]
Getting this error on console when trying up pickup spawners with silk touch.
https://pastebin.com/1SFVJ9u0

 - Server version: version git-Spigot-56f8471-43183ea (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
 - Plugin version DEV - 8 (git aded4b16)

**Comment by poma123** [comment]
Most likely there is some issue with your daily_limits.yml file. Could you paste it on pastebin? The config.yml also needed.

**Comment by yaitsbilly** [comment]
I did change it, will delete config and let it regenerate a new one. Plugin loads fine, I sell the spawners via ShopGUI+ and players can use them no problems. It’s only with picking up.

**Comment by CaszGamerMD** [comment]
same issue, went from 1.14.4 to 1.15.1
https://pastebin.com/zkTK3KAm on break
cant use ps's gui {no error in log}

deleted config and reloading

no change

on repo #9

**Comment by poma123** [comment]
@CaszGamerMD 
You should update to the latest version.
https://poma123.github.io/builds/poma123/PickupSpawners/master/#9

**Comment by CaszGamerMD** [comment]
I realized the old one was lingering in my plugs, I'm sorry. New one did
fix ty

**Comment by poma123** [comment]
@yaitsbilly I don't know what to do, if the issue is still occuring, please open a new ticket.

**Comment by weyaj** [comment]
THIS PLUGIN IS A COPY DONT USE IT


andrus ne vegyel monitort a szerverpenzbol andrus @andris155 andrus nem adtam ra engedelyt h torold a kommentem gecukam
