### ISSUE TITLE
Pickaxe damage doesn't work

### ISSUE THREAD

**Issue by regitraz** [poma123/PickupSpawners#8]
Hi !

I'm currently running an 1.14.2 survival server, I have add a pickaxe with the command "/pspawner additem" this pickaxe has only 1 use left (a golden pickaxe with 31/32 damage) but it appaers that the damage of the pickaxe doesn't have any effect. If the pickaxe has 32/32 durability spawners are minable

**Comment by poma123** [comment]
Currently, the plugin saves only the display name, enchants and lore of the item.

**Comment by poma123** [comment]
Working on it
