### ISSUE TITLE
Spawner biomes

### ISSUE THREAD

**Issue by volx4** [poma123/PickupSpawners#9]
I'm running on 1.14.4 and passive mobs like rabbits or pigs don't spawn in the desert (even though desert rabbits can spawn) can you add something into the config files to disable this.
Slimes only spawn in swamps as well.

Thanks!

**Comment by poma123** [comment]
This plugin handles spawner breaking and placing only. It doesn't have any effect on mob spawning.

**Comment by weyaj** [comment]
andrus ne vegyel monitort a szerverpenzbol andrus @andris155 andrus nem adtam ra engedelyt h torold a kommentem gecukam
